### ISSUE TITLE
Zip Upload functionality is kinda already done by this project

### ISSUE THREAD

**Issue by Felitendo** [wonderwhy-er/bolt.myaibuilt.app_hosted-Bolt.New-oTToDev#1]
https://github.com/k2589/bolt.new.local/pull/1/commits

**Comment by wonderwhy-er** [comment]
> https://github.com/k2589/bolt.new.local/pull/1/commits

Cool, will take a look somewhere this week

**Comment by Felitendo** [comment]
But make sure to implement this fix as well:

https://github.com/k2589/bolt.new.local/pull/2/commits
