### ISSUE TITLE
Let us use our antrophopic API Keys

### ISSUE THREAD

**Issue by Felitendo** [wonderwhy-er/bolt.myaibuilt.app_hosted-Bolt.New-oTToDev#2]
Right now you can only use the OpenRouter API key as far as i know. But I want to use the Antrophopic API Key like in the upstream repo.

**Comment by wonderwhy-er** [comment]
Yeah, I am slowly planning to add more providers again.

There will probably be a dropdown to select the provider, and then API key

It will also help me as more providers have free models so I can provide free variants for people with API keys with better consistency

I think that first batch will be Antropic, OpenAI and Google provider

But there are many others to add too

I have a bit busy week, I may only get to it next week.

It is at the top of my list currently

**Comment by wonderwhy-er** [comment]
I just updated Readme with ongoing work and this is on first spot

**Comment by wonderwhy-er** [comment]
Cole fork merged in to this one so there is ability to use antropic keys now
