### ISSUE TITLE
None of the models are showing up after pnpm run dev

### ISSUE THREAD

**Issue by lisaiceland** [wonderwhy-er/bolt.myaibuilt.app_hosted-Bolt.New-oTToDev#3]
### Describe the bug

None of the models are showing up after pnpm run dev

### Link to the Bolt URL that caused the error

**localhost**

### Steps to reproduce

pnpm install
pnpm run dev

### Expected behavior

it should run with all the models available showing up

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by wonderwhy-er** [comment]
Thanks for detailed report, I will take a look at showing errors if this part fails and we will see then, does work for me on Mac
