### ISSUE TITLE
XAI grok-beta support

### ISSUE THREAD

**Issue by rahulrez** [wonderwhy-er/bolt.myaibuilt.app_hosted-Bolt.New-oTToDev#4]
Could you please add support for XAI grok-beta they are giving $25 per month credits which are good enough.
If it is already done by someone please let me know.
The Prompt Enhance button does not work, it clears the prompt itself

**Comment by wonderwhy-er** [comment]
I just rebased on oTToDev fork, it should have xAI now, did not test yet

**Comment by rahulrez** [comment]
it works fine I have tested
